version: 2
updates:
- package-ecosystem: maven
  directory: "/modules/core"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/modules/gateway"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
