version: 2
updates:
- package-ecosystem: maven
  directory: "/modules/gs-tree"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/modules/gs-gateway"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/modules/gs-user"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
