version: 2
updates:
- package-ecosystem: maven
  directory: "/modules/gs-tree"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: maven
  directory: "/modules/gs-user-q"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: gradle
  directory: "/modules/gs-gateway"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: gradle
  directory: "/modules/gs-user"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  pull-request-branch-name:
    separator: "-"
