server:
  port: 8080
spring:
  application:
    name: gs-user
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 49d2f6faed284d742b47
            clientSecret: 0080e414065d4ae5f2e33adad53aaff54a3ce992
          google:
            client-id: 302799538738-gcqp2diq53pstj08vdg0tn1mc1moh2gf.apps.googleusercontent.com
            client-secret: XIY9Nw3ahDtlv6DWUKBbWZDe
  main:
    #    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
core-url:
  host: ${CORE_URL_HOST:localhost}
  port: ${CORE_URL_PORT:8080}
opentracing:
  jaeger:
    enabled: true
    #    enable-b3-propagation: true
    #    udp-sender:
    #      host: ${JAEGER_UDP_HOST:localhost}
    #      port: 6831
    #opentracing:
    #  jaeger:
    #    service-name: gateway
    #    enabled: true
    ##    udp-sender:
    ##      host: jaeger
    ##      port: 6831
    http-sender:
      url: http://${JAEGER_UDP_HOST:localhost}:14268/api/traces
  spring:
    cloud:
      gateway:
        enabled: true
#    http-sender:
#      #url: http://localhost:14268/api/traces
#      url: http://${JAEGER_HOST}:14268/api/traces
logging:
  level:
    io.opentracing: TRACE
    org.springframework.security: DEBUG
    root: DEBUG
    io.jaegertracing: DEBUG
    com.samal.greenstone: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    reactor.netty: DEBUG
    redisratelimiter: DEBUG



