spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres?user=compose-postgres&password=compose-postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
opentracing:
  jaeger:
    enabled: false
