server:
  port: 8080
spring:
  application:
    name: gs-tree
  output:
    ansi:
      enabled: ALWAYS
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          github:
  #            clientId: 49d2f6faed284d742b47
  #            clientSecret: 0080e414065d4ae5f2e33adad53aaff54a3ce992
  #          google:
  #            client-id: 302799538738-gcqp2diq53pstj08vdg0tn1mc1moh2gf.apps.googleusercontent.com
  #            client-secret: XIY9Nw3ahDtlv6DWUKBbWZDe
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        order_inserts: true
        order_update: true
        jdbc:
          batch_size: 50
          fetch_size: 50
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/compose-postgres
    driver-class-name: org.postgresql.Driver
    #    username: <username>
    #    password: <password>
    hikari:
      idle-timeout: 10000
opentracing:
  jaeger:
    log-spans: true
    enabled: true
    #    udp-sender:
    #      host: ${JAEGER_UDP_HOST:localhost}
    #      port: 6831
    #opentracing:
    #  jaeger:
    #    service-name: gs-tree
    #    enabled: true
    ##    udp-sender:
    ##      host: jaeger
    ##      port: 6831
    http-sender:
      url: http://${JAEGER_UDP_HOST:localhost}:14268/api/traces
#      #url: http://localhost:14268/api/traces
logging:
  level:
    io.opentracing: TRACE
    #    org.springframework.security: WARN
    root: WARN
    io.jaegertracing: TRACE
    com.samal.greenstone: INFO

  # Output to a file named application.log.
  file.name: application.log

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: MonitoringSpringDemoProject
springdoc:
  packagesToScan: package1, package2
  pathsToMatch: /trees