apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.network/greenstone-network: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: compose-postgres
            - name: POSTGRES_USER
              value: compose-postgres
          image: postgres:13.1-alpine
          name: db
          ports:
            - containerPort: 5432
