apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gs-gateway
  name: gs-gateway
spec:
  ports:
    - name: "44401"
      port: 44401
      targetPort: 8080
  selector:
    io.kompose.service: gs-gateway
