apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/asamal/IdeaProjects/greenstone/docker/dc-remote.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gs-tree
  name: gs-tree
spec:
  type: NodePort
  ports:
    - name: "44402"
      port: 44402
      targetPort: 8080
    - name: debug
      port: 5005
      targetPort: 5005
      nodePort: 31005
      protocol: TCP
  selector:
    io.kompose.service: gs-tree
status:
  loadBalancer: {}
