resources:
  - prometheus-clusterrole.yaml
  - prometheus-configmap.yaml
  - prometheus-service.yaml
  - prometheus-deployment.yaml
  - prometheus-data-persistentvolumeclaim.yaml
  - prometheus-claim0-persistentvolumeclaim.yaml
  - jaeger-service.yaml
  - jaeger-deployment.yaml
  - gs-user-service.yaml
  - gs-user-q-service.yaml
  - gs-user-q-deployment.yaml
  - gs-user-deployment.yaml
  - gs-tree-service.yaml
  - gs-tree-deployment.yaml
  - gs-gateway-service.yaml
  - gs-gateway-deployment.yaml
  - greenstone-network-networkpolicy.yaml
  - graphana-service.yaml
  - graphana-deployment.yaml
  - grafana-data-persistentvolumeclaim.yaml
  - db-service.yaml
  - db-deployment.yaml