version: "3.8"
services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - jaeger-example
  core:
    build:
      dockerfile: docker/Dockerfile
      context: ../modules/core
    ports:
      - "8082:8080"
    environment:
#      - JAEGER_SERVICE_NAME=core
      - JAEGER_UDP_HOST=jaeger
#      - JAEGER_UDP_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks:
      - jaeger-example
    depends_on:
      - jaeger
  gateway:
    build:
      dockerfile: docker/Dockerfile
      context: ../modules/gateway
    ports:
      - "8081:8080"
    environment:
      - CORE_URL=http://jaeger:8082
#      - JAEGER_SERVICE_NAME=gateway
      - JAEGER_UDP_HOST=jaeger
#      - JAEGER_UDP_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks:
      - jaeger-example
    depends_on:
      - jaeger
networks:
  jaeger-example: