version: "3.8"
services:
  core:
    build:
      dockerfile: docker/Dockerfile
      context: ../modules/core
    ports:
      - "8082:8080"
  gateway:
    build:
      dockerfile: docker/Dockerfile
      context: ../modules/gateway
    ports:
      - "8081:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"