version: "3.8"
services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - jaeger-example
  core:
    image: sanek555/gscore:latest
    ports:
      - "44402:8080"
    environment:
      #      - JAEGER_SERVICE_NAME=core
      - JAEGER_UDP_HOST=jaeger
      #      - JAEGER_UDP_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks:
      - jaeger-example
    depends_on:
      - jaeger
  gateway:
    image: sanek555/gsgateway:latest
    ports:
      - "44401:8080"
    environment:
      #      - JAEGER_SERVICE_NAME=gateway
      - JAEGER_UDP_HOST=jaeger
      #      - JAEGER_UDP_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - CORE_URL_HOST=core
    networks:
      - jaeger-example
    depends_on:
      - jaeger
networks:
  jaeger-example: