spring:
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 49d2f6faed284d742b47
            clientSecret: 0080e414065d4ae5f2e33adad53aaff54a3ce992
          google:
            client-id: 302799538738-gcqp2diq53pstj08vdg0tn1mc1moh2gf.apps.googleusercontent.com
            client-secret: XIY9Nw3ahDtlv6DWUKBbWZDe
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        generate_statistics: false
        order_inserts: true
        order_update: true
        jdbc:
          batch_size: 50
          fetch_size: 50
#logging:
#  level:
#    org.springframework.security: DEBUG