server:
  port: 8080
spring:
  application:
    name: core
  output:
    ansi:
      enabled: ALWAYS
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 49d2f6faed284d742b47
#            clientSecret: 0080e414065d4ae5f2e33adad53aaff54a3ce992
#          google:
#            client-id: 302799538738-gcqp2diq53pstj08vdg0tn1mc1moh2gf.apps.googleusercontent.com
#            client-secret: XIY9Nw3ahDtlv6DWUKBbWZDe
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        order_inserts: true
        order_update: true
        jdbc:
          batch_size: 50
          fetch_size: 50
opentracing:
  jaeger:
    log-spans: true
    enabled: true
#    udp-sender:
#      host: ${JAEGER_UDP_HOST:localhost}
#      port: 6831
#opentracing:
#  jaeger:
#    service-name: core
#    enabled: true
##    udp-sender:
##      host: jaeger
##      port: 6831
    http-sender:
      url: http://${JAEGER_UDP_HOST:localhost}:14268/api/traces
#      #url: http://localhost:14268/api/traces
logging:
  level:
    io.opentracing: TRACE
#    org.springframework.security: WARN
    root: WARN
    io.jaegertracing: TRACE
    com.samal.greenstone: INFO